# Generated by Django 5.2 on 2025-05-13 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('picklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('pick_time', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.DurationField()),
                ('successful', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.device')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('time_taken', models.DurationField()),
                ('successful', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orderpiqrApp.picklist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.product')),
            ],
        ),
    ]
