# Generated by Django 5.2 on 2025-05-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0002_device_user_picklist_productpick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='code',
        ),
    ]
