# Generated by Django 5.2 on 2025-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0005_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
