# Generated by Django 5.2 on 2025-05-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0006_device_device_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='picklist_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
