# Generated by Django 5.2 on 2025-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0008_picklist_created_at_picklist_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='pick_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='successful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='successful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
