# Generated by Django 5.2 on 2025-05-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0009_alter_picklist_pick_time_alter_picklist_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer'),
            preserve_default=False,
        ),
    ]
