# Generated by Django 5.2 on 2025-06-01 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0010_picklist_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='picklist',
            options={'verbose_name': 'Pick List', 'verbose_name_plural': 'Pick Lists'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productpick',
            options={'verbose_name': 'Product Pick', 'verbose_name_plural': 'Product Picks'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Device Fingerprint'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_login',
            field=models.DateTimeField(verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lists_picked',
            field=models.IntegerField(verbose_name='Lists Picked'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='pick_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Pick Time'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='picklist_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Picklist Code'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='successful',
            field=models.BooleanField(blank=True, null=True, verbose_name='Successful'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='time_taken',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Taken'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.IntegerField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='picklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orderpiqrApp.picklist', verbose_name='Pick List'),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='successful',
            field=models.BooleanField(blank=True, null=True, verbose_name='Successful'),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='time_taken',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Taken'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=255, unique=True, verbose_name='Order Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='picklist',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderpiqrApp.order', verbose_name='Source Order'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orderpiqrApp.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderpiqrApp.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
            },
        ),
    ]
