# Generated by Django 5.2 on 2025-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0011_alter_customer_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='pick_started',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pick Started'),
        ),
    ]
