# Generated by Django 5.2 on 2025-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0012_picklist_pick_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
    ]
