# Generated by Django 5.2 on 2025-08-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0013_alter_product_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Internal name for this setting (e.g. 'language', 'sort_by_location').", max_length=100, unique=True, verbose_name='Key')),
                ('label', models.CharField(help_text="Human-readable label shown in admin or forms (e.g. 'Language').", max_length=255, verbose_name='Label')),
                ('help_text', models.TextField(blank=True, help_text='Additional description or guidance for this setting.', verbose_name='Help text')),
                ('setting_type', models.CharField(choices=[('str', 'String'), ('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'DateTime'), ('color', 'Color (HEX)'), ('url', 'URL'), ('img', 'Image'), ('json', 'JSON')], default='str', help_text='The type of this setting (e.g. boolean, integer, string).', max_length=10, verbose_name='Type')),
                ('default_value', models.CharField(blank=True, help_text='Used if customer-specific value is not set.', max_length=255, null=True, verbose_name='Default value')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='The value set for this customer.', max_length=255, verbose_name='Value')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='orderpiqrApp.customer', verbose_name='Customer')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_values', to='orderpiqrApp.settingdefinition', verbose_name='Setting')),
            ],
            options={
                'verbose_name': 'Customer setting value',
                'verbose_name_plural': 'Customer setting values',
                'unique_together': {('customer', 'definition')},
            },
        ),
    ]
