# Generated by Django 5.2 on 2025-12-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0014_settingdefinition_customersettingvalue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='picklist',
            unique_together={('picklist_code', 'customer')},
        ),
    ]
