# Generated by Django 5.2 on 2026-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0015_alter_picklist_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['queue_position', 'created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='order',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the picking queue. Lower numbers are picked first.', null=True, verbose_name='Queue Position'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
