# Generated by Django 5.2 on 2026-01-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0016_add_order_queue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingdefinition',
            name='options',
            field=models.JSONField(blank=True, help_text='For \'choice\' type settings: list of {value, label} options. E.g. [{"value": "original", "label": "Original order"}]', null=True, verbose_name='Options'),
        ),
    ]
