# Generated by Django 5.2 on 2026-02-25 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0018_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity for this product.', verbose_name='Inventory Quantity'),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_quantity', models.IntegerField(verbose_name='Old Quantity')),
                ('new_quantity', models.IntegerField(verbose_name='New Quantity')),
                ('change_type', models.CharField(choices=[('set', 'Set (absolute)'), ('adjust', 'Adjust (relative)')], max_length=10, verbose_name='Change Type')),
                ('reason', models.CharField(choices=[('stock_count', 'Stock Count'), ('received', 'Goods Received'), ('damaged', 'Damaged'), ('returned', 'Customer Return'), ('correction', 'Correction'), ('order_picked', 'Order Picked'), ('other', 'Other')], max_length=20, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderpiqrApp.device', verbose_name='Device')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='orderpiqrApp.product', verbose_name='Product')),
                ('source_picklist', models.ForeignKey(blank=True, help_text='If this change was caused by order completion, reference to the picklist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderpiqrApp.picklist', verbose_name='Source Picklist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
