# Generated by Django 5.2.12 on 2026-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0023_add_bulk_pick_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=255, verbose_name='Order Code'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('customer', 'order_code'), name='unique_order_code_per_customer'),
        ),
    ]
