# Generated by Django 5.2.12 on 2026-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0024_alter_order_order_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, default='manual', help_text='Where this order came from: manual, csv, api, or an integration platform (e.g. shopify).', max_length=32, verbose_name='Source'),
        ),
    ]
