# Generated by Django 5.2.12 on 2026-09-14 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0025_order_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('device_fingerprint', 'customer'), name='unique_device_fingerprint_per_customer'),
        ),
    ]
