# Generated by Django 5.2.12 on 2026-09-23 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0026_device_fingerprint_unique_per_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickerLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token Hash')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Times Used')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer', verbose_name='Customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picker_login_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Picker')),
            ],
            options={
                'verbose_name': 'Picker Login QR',
                'verbose_name_plural': 'Picker Login QRs',
                'ordering': ['-created'],
            },
        ),
    ]
