# Generated by Django 5.2.12 on 2026-09-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0031_picklist_field_order_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('unknown_product', 'Unknown product'), ('wrong_product', 'Wrong product scanned'), ('picklist_parse_error', 'Picklist could not be read'), ('picklist_rejected', 'Picklist rejected'), ('sync_error', 'Sync error'), ('manual_override', 'Manual override')], max_length=32, verbose_name='Event Type')),
                ('scanned_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Scanned Code')),
                ('picklist_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Picklist Code')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderpiqrApp.customer', verbose_name='Customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderpiqrApp.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Scan Event',
                'verbose_name_plural': 'Scan Events',
                'indexes': [models.Index(fields=['customer', 'created_at'], name='orderpiqrAp_custome_c6412c_idx'), models.Index(fields=['customer', 'event_type', 'created_at'], name='orderpiqrAp_custome_44d55c_idx')],
            },
        ),
    ]
