# Generated by Django 5.2.12 on 2026-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderpiqrApp', '0032_scan_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
