from .customer_admin import *
from .device_admin import *
from .general_admin import *
from .order_admin import *
from .picklist_admin import *
from .product_admin import *
from .userprofile_admin import *
from .preferences_admin import *
from .email_admin import *
