# Generated by Django 5.2 on 2026-09-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0003_syncjob'),
        ('orderpiqrApp', '0026_device_fingerprint_unique_per_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_pairing_tokens', to='orderpiqrApp.customer')),
            ],
            options={
                'verbose_name': 'Pairing token',
                'verbose_name_plural': 'Pairing tokens',
            },
        ),
        migrations.CreateModel(
            name='WooCommerceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_url', models.CharField(max_length=255)),
                ('store_name', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_consumer_key', models.TextField(blank=True, default='')),
                ('encrypted_consumer_secret', models.TextField(blank=True, default='')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64)),
                ('plugin_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('wordpress_version', models.CharField(blank=True, default='', max_length=32)),
                ('woocommerce_version', models.CharField(blank=True, default='', max_length=32)),
                ('plugin_version', models.CharField(blank=True, default='', max_length=32)),
                ('webhook_ids', models.JSONField(blank=True, default=list)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_store', to='integrations.connection')),
            ],
            options={
                'verbose_name': 'WooCommerce store',
                'verbose_name_plural': 'WooCommerce stores',
            },
        ),
    ]
