from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from api.serializers import DeviceSerializer, DeviceCreateSerializer
from orderpiqrApp.models import Device, PickList
from rest_framework import filters
from django.db.models import Count, Avg, Q, Sum
from django.utils import timezone
from datetime import timedelta

from drf_spectacular.utils import extend_schema, extend_schema_view, OpenApiExample, OpenApiResponse, OpenApiParameter


@extend_schema_view(
    list=extend_schema(
        summary="List all devices",
        description="""
        Retrieve a list of all registered devices for the authenticated user's customer.

        **Search:** Use the `?search=` query parameter to filter by device name or description.

        **Filtering:**
        - `?user=1` - Filter by user ID
        - `?user__isnull=true` - Devices without an assigned user

        **Ordering:**
        - `?ordering=-last_login` - Sort by last activity (most recent first)
        - `?ordering=-lists_picked` - Sort by number of picks

        Devices represent physical picking devices (mobile phones, tablets, scanners)
        used in the warehouse for picking operations.
        """
    ),
    retrieve=extend_schema(
        summary="Get device details",
        description="Retrieve details of a specific device, including recent activity."
    ),
    create=extend_schema(
        summary="Register a new device",
        description="""
        Register a new picking device.

        The device fingerprint is a unique identifier generated by the device
        (usually based on browser/device characteristics).

        The `customer` field is automatically set based on the authenticated user's profile.
        """
    ),
    update=extend_schema(
        summary="Update a device",
        description="Update device details such as name and description."
    ),
    partial_update=extend_schema(
        summary="Partially update a device",
        description="Update specific fields of a device."
    ),
    destroy=extend_schema(
        summary="Delete a device",
        description="""
        Delete a device from the system.

        **Note:** Devices with pick list history cannot be deleted to maintain audit trails.
        """
    ),
)
@extend_schema(
    tags=["devices"],
    examples=[
        OpenApiExample(
            name="Device Example",
            description="A picking device registration",
            value={
                "name": "Warehouse Scanner #1",
                "description": "Main floor picking device",
                "device_fingerprint": "abc123def456..."
            },
            request_only=True
        )
    ]
)
class DeviceViewSet(viewsets.ModelViewSet):
    queryset = Device.objects.none()  # Required for drf-spectacular
    serializer_class = DeviceSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['name', 'description']
    ordering_fields = ['name', 'last_login', 'lists_picked', 'device_id']
    ordering = ['-last_login']

    def get_queryset(self):
        queryset = Device.objects.filter(
            customer=self.request.user.userprofile.customer
        ).select_related('user')

        # Manual filtering
        user_id = self.request.query_params.get('user')
        if user_id:
            queryset = queryset.filter(user_id=user_id)

        unassigned = self.request.query_params.get('unassigned')
        if unassigned is not None and unassigned.lower() == 'true':
            queryset = queryset.filter(user__isnull=True)

        return queryset

    def get_serializer_class(self):
        if self.action == 'create':
            return DeviceCreateSerializer
        return DeviceSerializer

    def perform_create(self, serializer):
        serializer.save(
            customer=self.request.user.userprofile.customer,
            user=self.request.user,
            last_login=timezone.now(),
            lists_picked=0
        )

    def destroy(self, request, *args, **kwargs):
        device = self.get_object()
        # Check if device has pick list history
        if device.picklist_set.exists():
            return Response(
                {'detail': 'Cannot delete device with pick list history. Unassign the user instead.'},
                status=status.HTTP_400_BAD_REQUEST
            )
        return super().destroy(request, *args, **kwargs)

    @extend_schema(
        summary="Lookup device by fingerprint",
        description="Find a device by its fingerprint. Useful for device authentication.",
        parameters=[
            OpenApiParameter(
                name='fingerprint',
                description='The device fingerprint to look up',
                required=True,
                type=str
            )
        ],
        responses={
            200: DeviceSerializer,
            404: OpenApiResponse(description="Device not found")
        }
    )
    @action(detail=False, methods=['get'])
    def lookup(self, request):
        """Look up a device by its fingerprint."""
        fingerprint = request.query_params.get('fingerprint')
        if not fingerprint:
            return Response(
                {'detail': 'Fingerprint parameter is required'},
                status=status.HTTP_400_BAD_REQUEST
            )

        try:
            device = Device.objects.get(
                device_fingerprint=fingerprint,
                customer=request.user.userprofile.customer
            )
            serializer = DeviceSerializer(device)
            return Response(serializer.data)
        except Device.DoesNotExist:
            return Response(
                {'detail': 'Device not found'},
                status=status.HTTP_404_NOT_FOUND
            )

    @extend_schema(
        summary="Register or update device",
        description="""
        Register a new device or update existing one by fingerprint.

        This endpoint is idempotent - it will create the device if it doesn't exist,
        or update the last_login timestamp if it does.
        """,
        request={
            "application/json": {
                "type": "object",
                "properties": {
                    "device_fingerprint": {"type": "string"},
                    "name": {"type": "string"},
                    "description": {"type": "string"}
                },
                "required": ["device_fingerprint"]
            }
        },
        responses={
            200: OpenApiResponse(
                description="Device registered/updated",
                examples=[
                    OpenApiExample(
                        name="Success Response",
                        value={
                            "status": "ok",
                            "device_id": 1,
                            "created": False,
                            "message": "Device updated"
                        }
                    )
                ]
            )
        }
    )
    @action(detail=False, methods=['post'])
    def register(self, request):
        """Register or update a device by fingerprint."""
        fingerprint = request.data.get('device_fingerprint')
        name = request.data.get('name', f'Device {fingerprint[:8]}...')
        description = request.data.get('description', '')

        if not fingerprint:
            return Response(
                {'detail': 'device_fingerprint is required'},
                status=status.HTTP_400_BAD_REQUEST
            )

        customer = request.user.userprofile.customer

        device, created = Device.objects.get_or_create(
            device_fingerprint=fingerprint,
            customer=customer,
            defaults={
                'name': name,
                'description': description,
                'user': request.user,
                'last_login': timezone.now(),
                'lists_picked': 0,
            }
        )

        if not created:
            device.last_login = timezone.now()
            device.user = request.user
            device.save(update_fields=['last_login', 'user'])

        return Response({
            'status': 'ok',
            'device_id': device.device_id,
            'created': created,
            'message': 'Device registered' if created else 'Device updated'
        })

    @extend_schema(
        summary="Get device statistics",
        description="Get statistics about all devices including activity and performance.",
        responses={
            200: OpenApiResponse(
                description="Device statistics",
                examples=[
                    OpenApiExample(
                        name="Statistics Response",
                        value={
                            "total_devices": 10,
                            "active_today": 5,
                            "active_this_week": 8,
                            "total_picks": 1500,
                            "top_performers": [
                                {"device_id": 1, "name": "Scanner #1", "picks": 450, "success_rate": 98.5}
                            ]
                        }
                    )
                ]
            )
        }
    )
    @action(detail=False, methods=['get'])
    def stats(self, request):
        """Get device statistics."""
        customer = request.user.userprofile.customer
        devices = Device.objects.filter(customer=customer)

        today = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)
        week_ago = today - timedelta(days=7)

        # Top performers by pick count
        top_performers = devices.order_by('-lists_picked')[:5]
        top_performers_data = []
        for device in top_performers:
            total_picks = PickList.objects.filter(device=device, successful__isnull=False).count()
            successful_picks = PickList.objects.filter(device=device, successful=True).count()
            success_rate = round((successful_picks / total_picks * 100) if total_picks > 0 else 0, 1)

            top_performers_data.append({
                'device_id': device.device_id,
                'name': device.name,
                'picks': device.lists_picked,
                'success_rate': success_rate
            })

        return Response({
            'total_devices': devices.count(),
            'active_today': devices.filter(last_login__gte=today).count(),
            'active_this_week': devices.filter(last_login__gte=week_ago).count(),
            'total_picks': devices.aggregate(total=Sum('lists_picked'))['total'] or 0,
            'top_performers': top_performers_data
        })

    @extend_schema(
        summary="Get device performance",
        description="Get detailed performance metrics for a specific device.",
        responses={
            200: OpenApiResponse(
                description="Device performance",
                examples=[
                    OpenApiExample(
                        name="Performance Response",
                        value={
                            "device_id": 1,
                            "name": "Scanner #1",
                            "total_picklists": 150,
                            "successful": 145,
                            "failed": 5,
                            "success_rate": 96.7,
                            "avg_time_per_pick": "00:04:30",
                            "picks_today": 12,
                            "picks_this_week": 45
                        }
                    )
                ]
            )
        }
    )
    @action(detail=True, methods=['get'])
    def performance(self, request, pk=None):
        """Get performance metrics for a specific device."""
        device = self.get_object()

        today = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)
        week_ago = today - timedelta(days=7)

        picklists = PickList.objects.filter(device=device)
        completed = picklists.filter(successful__isnull=False)
        successful = picklists.filter(successful=True)

        total_completed = completed.count()
        success_rate = round(
            (successful.count() / total_completed * 100) if total_completed > 0 else 0, 1
        )

        avg_time = completed.filter(time_taken__isnull=False).aggregate(
            avg=Avg('time_taken')
        )['avg']

        return Response({
            'device_id': device.device_id,
            'name': device.name,
            'total_picklists': picklists.count(),
            'successful': successful.count(),
            'failed': completed.count() - successful.count(),
            'success_rate': success_rate,
            'avg_time_per_pick': str(avg_time) if avg_time else None,
            'picks_today': picklists.filter(created_at__gte=today).count(),
            'picks_this_week': picklists.filter(created_at__gte=week_ago).count()
        })

    @extend_schema(
        summary="Unassign user from device",
        description="Remove the user assignment from a device.",
        responses={
            200: OpenApiResponse(
                description="User unassigned",
                examples=[
                    OpenApiExample(
                        name="Success Response",
                        value={"status": "ok", "message": "User unassigned from device"}
                    )
                ]
            )
        }
    )
    @action(detail=True, methods=['post'])
    def unassign_user(self, request, pk=None):
        """Unassign the user from a device."""
        device = self.get_object()
        device.user = None
        device.save(update_fields=['user'])

        return Response({
            'status': 'ok',
            'message': 'User unassigned from device'
        })
