from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.db import transaction
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.models import Group

from orderpiqrApp.forms.accounts.signup_form import CompanySignupForm
from orderpiqrApp.models import Customer, UserProfile  # adjust to your actual paths
from django.utils.translation import gettext as _
import logging
from django.db import IntegrityError, DataError, transaction
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

logger = logging.getLogger(__name__)

User = get_user_model()

# If your profile model uses roles, you can set them here (optional):
ROLE_ADMIN = 'ADMIN'
ROLE_PICKER = 'PICKER'
PROFILE_USERNAME_FIELD = 'username'


def signup(request):
    if request.method == 'POST':
        form = CompanySignupForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    # Create company
                    customer = Customer.objects.create(name=form.cleaned_data['company_name'], )
                    # Enforce per-company unique usernames now that we have a customer
                    form.ensure_profile_username_available(customer, form.cleaned_data['admin_profile_username'],
                                                           'admin_profile_username', )
                    form.ensure_profile_username_available(customer, form.cleaned_data['picker_profile_username'],
                                                           'picker_profile_username', )

                    # Create Admin user (email is optional; username for auth will be autogenerated if your AUTH_USER_MODEL requires)
                    admin_user = User.objects.create_user(
                        username=form.cleaned_data["admin_profile_username"],
                        email=form.cleaned_data["admin_email"],
                        password=form.cleaned_data["admin_password1"],
                        is_staff=True,
                    )
                    picker_user = User.objects.create_user(
                        username=form.cleaned_data["picker_profile_username"],
                        email=form.cleaned_data["picker_email"],
                        password=form.cleaned_data["picker_password1"],
                    )
                    admin_group = Group.objects.get(name="companyadmin")
                    picker_group = Group.objects.get(name="orderpicker")
                    admin_user.groups.add(admin_group)
                    picker_user.groups.add(picker_group)
                    UserProfile.objects.create(user=admin_user, customer=customer)
                    UserProfile.objects.create(user=picker_user, customer=customer)

                messages.success(request, _("Your company and users were created. Welcome! "
                                            "Start the onboarding by pressing the green button on the lower right of your screen.")
                                 )
                login(request, admin_user)
                return redirect(reverse("admin:index"))
            except IntegrityError:
                # Likely duplicate username/email/company
                form.add_error(None, _("That username or email is already in use. Please choose a different one."))
                logger.warning("Signup IntegrityError", exc_info=True)
            except DataError: # Too long / invalid DB value
                form.add_error(None,
                               _("Some of the submitted data is invalid or too long. Please review and try again."))
                logger.warning("Signup DataError", exc_info=True)
            except ValidationError as e:
                if hasattr(e, "message_dict"):
                    for field, msgs in e.message_dict.items():
                        for m in msgs:
                            form.add_error(field if field in form.fields else None, m)
                else:
                    form.add_error(None, _("Please correct the highlighted errors and try again."))
                logger.info("Signup ValidationError: %s", e, exc_info=True)

            except (ValueError, KeyError, AttributeError): # Bad/missing values, wrong keys, or attribute access
                form.add_error(None,
                               _("Some of the submitted information is missing or invalid. Please check and try again."))
                logger.warning("Signup input error", exc_info=True)
            except Exception:
                form.add_error(None, _("We’re experiencing technical issues. Please try again shortly."))
                logger.exception("Unexpected error during signup")
    else:
        form = CompanySignupForm()

    return render(request, 'registration/signup.html', {'form': form})
