# Generated by Django 5.2.12 on 2026-08-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(max_length=255, unique=True)),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('encrypted_refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('shop_email', models.CharField(blank=True, default='', max_length=255)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_shop', to='integrations.connection')),
            ],
            options={
                'verbose_name': 'Shopify shop',
                'verbose_name_plural': 'Shopify shops',
            },
        ),
    ]
