# Generated by Django 5.2 on 2026-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyshop',
            name='subscription_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyshop',
            name='subscription_plan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shopifyshop',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
