# Generated by Django 5.2.12 on 2026-08-07 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderpiqrApp', '0025_order_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('bol', 'Bol.com')], max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='orderpiqrApp.customer')),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
            },
        ),
        migrations.CreateModel(
            name='ExternalOrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=255)),
                ('external_order_number', models.CharField(blank=True, default='', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='integrations.connection')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='orderpiqrApp.order')),
            ],
            options={
                'verbose_name': 'External order link',
                'verbose_name_plural': 'External order links',
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_order_id'), name='unique_external_order_per_connection')],
            },
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('external_variant_id', models.CharField(max_length=255)),
                ('identifier_value', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('match_method', models.CharField(blank=True, choices=[('barcode', 'Barcode'), ('sku', 'SKU'), ('metafield', 'Metafield'), ('variant_id', 'Variant ID'), ('auto_created', 'Auto-created product'), ('manual', 'Manual')], default='', max_length=32)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='integrations.connection')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='orderpiqrApp.product')),
            ],
            options={
                'verbose_name': 'Product link',
                'verbose_name_plural': 'Product links',
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_variant_id'), name='unique_variant_per_connection')],
            },
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('fulfill_order', 'Fulfill order'), ('archive_order', 'Archive order'), ('push_inventory', 'Push inventory level')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='integrations.connection')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_outbox', to='orderpiqrApp.order')),
            ],
            options={
                'verbose_name': 'Outbound task',
                'verbose_name_plural': 'Outbound tasks',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='integration_status_1930e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('external_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('needs_mapping', 'Needs product mapping'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='integrations.connection')),
            ],
            options={
                'verbose_name': 'Inbound event',
                'verbose_name_plural': 'Inbound events',
                'indexes': [models.Index(fields=['status', 'received_at'], name='integration_status_6897ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('connection', 'external_event_id'), name='unique_inbox_event_per_connection')],
            },
        ),
    ]
