# Generated by Django 5.2.12 on 2026-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='auto_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
