# Generated by Django 5.2 on 2026-09-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_connection_auto_provisioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product_sync', 'Product sync')], default='product_sync', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('linked', models.PositiveIntegerField(default=0)),
                ('unresolved', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.connection')),
            ],
            options={
                'verbose_name': 'Sync job',
                'verbose_name_plural': 'Sync jobs',
                'indexes': [models.Index(fields=['status', 'created_at'], name='integration_status_713bf3_idx')],
            },
        ),
    ]
